version: 2.1
executors:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo
  deploy:
    docker:
      - image: circleci/python
    working_directory: ~/repo
jobs:
  build:
    executor: build
    steps:
      - checkout
      - run: npm run publish
      - save_cache:
          key: v1-repo-{{.Environment.CIRCLE_SHA1}}
          paths:
            - ~/repo
  deploy:
    executor: deploy
    steps:
      - run: pip3 install awscli --upgrade --user
      - restore_cache:
          key: v1-repo-{{.Environment.CIRCLE_SHA1}}
      - run: ls -a
workflows:
  version: 2
  release:
    jobs:
      - build
      - deploy:
          requires:
            - build


#version: 2.1
#jobs:
#  build:
#    docker:
#      - image: circleci/node
#    steps:
#      - checkout
#      - run: cd ls-Open-Api-Docs
#      - run: npm run publish
#      - run: # distの下をキャッシュする



#  deploy:
#    docker:
#      - image: circleci/python
#    steps:
#      - run: pip3 install awscli --upgrade --user
#      - run: #ロードする
#      - run: #アップロードする