version: 2.1
executors:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo
  deploy:
    docker:
      - image: circleci/python
    working_directory: ~/repo
jobs:
  build:
    executor: build
    steps:
      - checkout
      - run: npm run publish
      - save_cache:
          key: v1-repo-{{.Environment.CIRCLE_SHA1}}
          paths:
            - ~/repo
      - run: echo $CIRCLE_BRANCH
  deploy:
    executor: deploy
    steps:
      - run: echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV
      - run: pip3 install awscli --upgrade --user
      - restore_cache:
          key: v1-repo-{{.Environment.CIRCLE_SHA1}}
      - run: echo ${PATH}
      - run: aws s3api create-bucket --bucket ${CIRCLE_BRANCH}
      #- run: aws s3 sync ~/repo s3://${CIRCLE_BRANCH}/ --exact-timestamps --delete
workflows:
  version: 2
  release:
    jobs:
      - build
      - prod-approval:
          type: approval
      - deploy:
          requires:
            - build
            - prod-approval

#version: 2.1
#jobs:
#  build:
#    docker:
#      - image: circleci/node
#    steps:
#      - checkout
#      - run: cd ls-Open-Api-Docs
#      - run: npm run publish
#      - run: # distの下をキャッシュする



#  deploy:
#    docker:
#      - image: circleci/python
#    steps:
#      - run: pip3 install awscli --upgrade --user
#      - run: #ロードする
#      - run: #アップロードする