version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        command: ls -a
    - run:
        command: cd repo/circle-ci-test
    - run:
        command: npm run publish
    - save_cache:
        key: v1-repo-{{.Environment.CIRCLE_SHA1}}
        paths:
        - ~/repo
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# executors:
#   build:
#     docker:
#       - image: circleci/node
#     working_directory: ~/repo
# jobs:
#   build:
#     executor: build
#     steps:
#       - checkout
#       - run: ls -a
#       - run: cd repo/circle-ci-test
#       - run: npm run publish
#       - save_cache:
#           key: v1-repo-{{.Environment.CIRCLE_SHA1}}
#           paths:
#             - ~/repo
#   
# 
# 
# #version: 2.1
# #jobs:
# #  build:
# #    docker:
# #      - image: circleci/node
# #    steps:
# #      - checkout
# #      - run: cd ls-Open-Api-Docs
# #      - run: npm run publish
# #      - run: # dist\u306E\u4E0B\u3092\u30AD\u30E3\u30C3\u30B7\u30E5\u3059\u308B
# 
# 
# 
# #  deploy:
# #    docker:
# #      - image: circleci/python
# #    steps:
# #      - run: pip3 install awscli --upgrade --user
# #      - run: #\u30ED\u30FC\u30C9\u3059\u308B
# #      - run: #\u30A2\u30C3\u30D7\u30ED\u30FC\u30C9\u3059\u308B